### ISSUE TITLE
can't knit Proceedings.Rmd 

### ISSUE THREAD

**Issue by ricardd** [pbs-assess/TTTworkshop#29]
Not expecting an answer, just opening this issue to document the ongoing problem I have when trying to knit the knitr example and now the proceedings document. 

```
output file: Proceedings.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Proceedings.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Proceedings.tex --template "C:\~\R\win-library\3.5\rmarkdown\rmd\latex\default-1.17.0.2.tex" --number-sections --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" --include-in-header "C:\Users\RicardD\AppData\Local\Temp\1\RtmpQBx0ua\rmarkdown-str27302d0a768a.html" --variable tables=yes --standalone --filter pandoc-citeproc 
! LaTeX Error: Option clash for package xcolor.

Error: Failed to compile Proceedings.tex. See Proceedings.log for more info.
Execution halted
```

and the tail of the log file:
```
! LaTeX Error: Option clash for package xcolor.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.129 \usepackage
                 {wrapfig} 
```

It was initially suggested that MiKTeX was to blame, but I am getting the same error after uninstalling MiKTeX and installing tinytex from R instead (which basically installs TeXLive).

**Comment by seananderson** [comment]
Many people, including myself, have this issue with the proceedings .tex file. It comes down to two packages internally loading the xcolor package — one without any options and one with the `[table]` option. I wasn't yet able to figure out which 2 packages were causing the clash by trial and error, but there are a number of LaTeX packages that are not needed and could be removed.

**Comment by grinnellm** [comment]
I commented out all the unused packages (as @seananderson said there were quite a few), so maybe try it again.

**Comment by ricardd** [comment]
Just tried again after pulling the latest changes, and I still get the same option clash error from xcolor.

**Comment by grinnellm** [comment]
Thanks for trying again @ricardd, and sorry this still doesn't work for you. This is beyond my area of expertise, but does it work if you load the package manually in the YAML header `\usepackage[table]{xcolor}`?

**Comment by seananderson** [comment]
Thanks for pulling out as much as possible @grinnellm . By trial and error I figured out that it's the `kable_styling( latex_options=c("striped","hold_position") )` combined with the `\hypersetup` that's causing xcolor to get loaded with table options. I commented those out here https://github.com/pbs-assess/TTTworkshop/commit/e28192f5712c442b8b07ec090c6b7a28a2df71a5 and it now builds for me.

**Comment by seananderson** [comment]
Well, it compiled a few times for me. I have the PDF to prove it!

![image](https://user-images.githubusercontent.com/19349/49395415-46c71600-f6eb-11e8-8698-5dfbcca47c64.png)

But unless I'm crazy I'm back to getting the same error. Still need to play with removing packages until I figure out what's causing it.

**Comment by seananderson** [comment]
And now it's working again for me. If anyone can figure out a reproducible way to generate the error, let me know. The only thing I did was delete the .log .tex and .pdf files (left behind when pandoc/LaTeX finds an error) and `rmarkdown::render("Proceedings.Rmd")` again.

**Comment by ricardd** [comment]
I wish I could say the same as @seananderson, I just fetched the latest repo, removed .log, .tex and .md files, and tried `rmarkdown::render("Proceedings.Rmd")` but I still get the same option clash error from xcolor.

**Comment by seananderson** [comment]
This is some really weird problem. I've managed to reliably re-create it now. I get the xtable option class error the first time I run `rmarkdown::render("Proceedings.Rmd")` but not in subsequent runs within the same R session. Of course, it always fails with the RStudio 'knit' button since that starts in a fresh session. @ricardd , can you try running `rmarkdown::render("Proceedings.Rmd")` multiple times in the same session? Make sure you have the most recent version of rmarkdown too. The only thing I can think of is that rmarkdown is setting some option in the R session after having been run once that changes the default LaTeX packages injected into the .tex file. We should capture that .tex file and compare it in the 2 cases.

**Comment by ricardd** [comment]
In TTTworkshop/proceedings, can the /doc and /doc/maindoc folders be removed?

**Comment by seananderson** [comment]
@ricardd , yes, I don't see those folders in the latest version: <https://github.com/pbs-assess/TTTworkshop/tree/master/proceedings> and I don't have them on my computer.

**Comment by andrew-edwards** [comment]
@ricardd I would guess so -  I don't even have them.

Last week I did get a weird error in that it would be build when I ran
`rmarkdown::render("Proceedings.Rmd"` 
in R (not RStudio, just R throught Xemacs), but then when I ran it a second time it didn't work. Had to restart R (which I think is what happens when you click the knitr button in RStudio).
Am guessing it's to do with the two packages discussed above. 

We could just take out the grey shading in the table if that's still causing issues. I haven't looked at how you have guys have simplified it down.

Thanks for all the enthusiasm!

**Comment by ricardd** [comment]
@seananderson, yes, it works now if I invoke the rmarkdown command twice. The second invocation also triggered the installation of a number of LaTeX packages through tlmgr. So I was unknowingly missing some LaTeX packages.

**Comment by ricardd** [comment]
Given that there is a solution to this now (don't use the RStudio "knit" button, but instead invoke `rmarkdown::render("Proceedings.Rmd")` twice with an error on the first pass), I will close issue #29.

**Comment by grinnellm** [comment]
Sounds good. We'll just have to remember to uncomment those lines for the final version so that URLs are in blue.

**Comment by seananderson** [comment]
I finally figured out the root of the problem. It's this: https://github.com/haozhu233/kableExtra/issues/274

If kableExtra is used then it loads xcolor in the preamble with different options than some other package is loading it with. The solution is to set the R option

```r
options(kableExtra.latex.load_packages = FALSE)
```

Somewhere before kableExtra gets used and then make sure the appropriate packages are already loaded in the TeX template (they already were here).

Should render fine now on the first go or via the 'knit' button in RStudio.

Solution here https://github.com/pbs-assess/TTTworkshop/commit/e1c7d0fd6445295d3197896ccad1a283327b48e1

**Comment by grinnellm** [comment]
Thanks Sean, that's great. Does it work if you add stripes back to the table?

**Comment by seananderson** [comment]
I can't get stripes added without loading the xcolor package with the table option, which creates the clash. I'm sure there's a solution, but it might not be worth figuring out here. `¯\_(ツ)_/¯`

**Comment by rcyost** [comment]
![image](https://user-images.githubusercontent.com/32645001/122606716-60c96980-d047-11eb-9ab4-5ddc2b21aa03.png)
![image](https://user-images.githubusercontent.com/32645001/122606778-79398400-d047-11eb-8e68-b39517740c6b.png)
![image](https://user-images.githubusercontent.com/32645001/122606807-8787a000-d047-11eb-9dd1-85eb103753e7.png)
![image](https://user-images.githubusercontent.com/32645001/122606829-92dacb80-d047-11eb-85a8-715a7549c0e9.png)

same issue, if I take away formatting it works, can't get any formatting for tables because xcolor

**Comment by rcyost** [comment]
tried restarting R session and running a few times from render and still doesn't work
