### ISSUE TITLE
Want 'under revision' to not get changed to 'in press', and neither to be capitalised in text

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/TTTworkshop#39]
I know we did something like this in gfsynopsis, so hoping @seananderson can easily fix it ;)
I know for CSAS you wouldn't put 'under revision' ones in the ref list, but I think it's fine here and won't clutter up the text. Added in 940765d.

**Comment by seananderson** [comment]
.csl format gives you one option for what you want to include if you don't have a publication date. If we need more than that then we have to use the notes field. I just updated it. https://github.com/pbs-assess/TTTworkshop/commit/511d8fffa462fa8eb94d53b45b8588bc2e995147

**Comment by andrew-edwards** [comment]
Seems to not say 'in press' for me, in ref list or in the text?!

**Comment by seananderson** [comment]
Well I'm out of ideas and time. Previously the change I made was: https://github.com/pbs-assess/gfsynopsis/commit/2db87554b75ae1359bd9d9fa9868e63b37019309 and that changed the output from "no date" to "In press" as I expected. But it appears that those are magic phrases because I can't get any other text to come through.

Unless somebody else can figure this out, a workaround would be to use 2019 as the date and add "In revision" to the pages or some other field that appears at the end.

**Comment by andrew-edwards** [comment]
I can fudge it.....

**Comment by seananderson** [comment]
Ha, that's a very effective hack.
